### ISSUE TITLE
[PTR Raid report - Mount Hyjal]: Solaris May 4th

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/PTR-review#10]
### Mechanics comments on trash mobs

**Ghoul:**

- Frenzy - works
- Canibalize - works

**Crypt fiend:**

- Web - does not work - As someone pointed out in my previous raid report this spell should not work in 3.3.5 so not gonna clasify as bug now.

**Abomination:**

- Disease cloud - works
- Knockdown - works

**Shadowy Necromancer:**

- Shadow bolt - works
- Cripple - works
- Summon Skeletons - works
- Unholy Frenzy - works
- Once MC he cant use any abilities. He should be able to cast Unholy Frenzy to allies. - works

**Banshee**

- Bashee Wail - works
- Anti-magic shell - works

**Gargoyle**

- Gargoyle strike - works

**Frost Wyrm**

- Frost Breath - works

**Giant Infernal**

- Stun on impact - works
- Immolation - works
- Flame Buffet - works

**Fel Stalker**

- Mana burn - works

Overall all trash abilities seem to work fine now.

### Tuning comments on trash mobs

Can basically repeat what I mentioned before:

Ghoul - Bit weak but fine.
Crypt Fiend - Bit weak but fine.
Abomination - 2nd highest threat trash. 5k aoe per tick per mob is quite strong, so they got the be separated quickly.
Shadowy Necromancer - By far the most dangerous trash. Shadow bolt dmg is fine but if all focus a healer its a kill. They also very quickly summon more adds. The melee are a joke but casters can also very quickly nuke a healer or ranged dps.
Banshee - piss easy
Gargoyle - Very annoying to deal with. Take forever to get into range and only ranged can deal with them. Only danger is if they all focus a healer but overall quite weak otherwise.
Frost Wyrm - They are ok. Will be bit problematic to deal with for melee heavy comps as they got 1m hp but overall fine.
Giant Infernal - They are ok as they are.
Fel Stalkers - Bit weak but fine.

### Mechanics comments on Rage Winterchill

Frost Armor -works
Death and Decay - Works
Icebolt - Works
Frost Nova - Works

### Tuning comments on Rage Winterchill

Nova dmg bit Strong. Could be lethal if comboed with D&D but keeps the priests on their toes. Personally I like both.
Iceblolt is still too strong and absolutely needs a **nerf**. Especially when this get cast right after D&D. Boss just picks a random person who unless shielded or tank just dies.

### Mechanics comments on Anetheron

Carrion swarm hit box seems to be weird now. The animation goes forward but people behind him ended up getting hit sometimes. Need some more triage but we didnt encounter this problem few weeks ago.

Sleep: now sleeps the whole raid within 55 yards. He should also not target the highest threat target. **NEW BUG**

His other abilities are still fine.

### Tuning comments on Anetheron

1 person can tank 2 infernals at the same time, which is fine imho. There still is the problem with initial agro and adds 1 shoting their initial target - usually healer.

### Mechanics comments on Kaz'rogal

Cripple - works
War stomp - works
Malevolent cleave - works
Mark of Kaz'rogal - works. Both issues with this abilities seem fixed.
Tauntable - works

### Tuning comments on Kaz'rogal

The fight is a dps race. From first glance weaker guilds might struggle on him but difficult to say for sure at this point.

### Mechanics comments on Azgalor

Cleave - works
Rain of Fire - works
Howl of Azgalor - works
Doom - Works

1 small asterisk for doom guard is that horde NPCs do not attack them. This is a **BUG** and they should agro them when in range.

### Tuning comments on Azgalor

Doomguards are still bit too strong. They spam stun very often which means a tank cant handle more than 2 at the same time. Having third in range means chain stun.

By far the biggest issue is still the Rain of Fire. The initial dmg is 600 less now - 2k but dot is the same. Overall this is still 11k dmg per 5 seconds (assuming person moves away asap). It is unsustainable with current values, especially given his wide range and the silence spam that hits the entire raid.

### Mechanics comments on Archimonde

Air Burst and Tears of the goddess both work fine
Fear - works
Grip of the legion - works
Doomfire Strike - Targeting random player works, however current tank should be excluded. He does dmg now however it goes ahead of the animation sometimes. Also the fire dmg ticks should become lower the longer the debuff persists. BUG
Finger of death - works
Soul Charge - works. All 3 variations work correctly if a player from the designated classes dies.

### Tuning comments on Archimonde

He hits like a truck. Its technically healable but with fear and dodging fire it might become too much. I recommend small AA nerf.
Fire dmg also seems to be bit too strong.

Given the fact that if a single person dies its almost guaranteed wipe I think the fight is bit undoable as it is. It is unrealistic for no1 to get bad RNG for such a long fight and cause a wipe.

### Overall comments on raid mechanics

It is a much better state than last time. A lot of issues were fixed with some new ones popping on anetheron but mechanic wise raid is in good spot right now.

### Give a rating out of 10 for the state of the mechanics in the raid

8

### Overall comments on tuning

Trash is fine.

Rage Winterchil Icebolt needs nerf.

Azgalor Rain of Fire needs nerf.

Anetheron and Azgalor adds might need smaller nerf to not cock block weaker raid groups.

Kaz'Rogal is almost perfect now.

Archimond needs AA and fire dmg nerfs.

### Give a rating out of 10 for the state of the tuning in the raid

8

**Comment by amed80** [comment]
> Giant Infernal
> Flame Buffet - works

did this really work ? i remember having 2 Giant infernals on me for 5mn and didn't get the debuff at all (unless for some reason i had the wrong infernals)

> Mechanics comments on Anetheron
> Carrion swarm hit box seems to be weird now.

yeah , currently this spell it will cast "correctly" towards a random player direction but the animation will always show it as it was casted on the tank, i think the boss always keep targeting the tank which causes this problem , he should target a random player before casting his Carrion Swarm.

his Sleep spell used to be casted only on himself , i guess with the latest change they forgot to add targets number which should be 3 , afaik the MT is included as it will be dispelled immediately with the boss auto attack.

> Kaz'rogal

can i know what was the raid comp when you tried Kaz'rogal ? i am interested of how you managed to deal with 13.4M hp and what is the timer for the kill :)

> Mechanics comments on Archimonde
> Doomfire Strike - Targeting random player works, however current tank should be excluded. He does dmg now however it goes ahead of the animation sometimes. Also the fire dmg ticks should become lower the longer the debuff persists. BUG

did the tick from the Doomfire debuff deal any damage over time ? i remember this only dealing damage once then nothing for the rest 45 sec.

**Comment by IskrenPlashkov** [comment]
When did you last test the Giant Infernals ? They were bugged few weeks ago but saturday they were fine.

For kaz'rogal we only had only 22 people so we struggled with the dps. I think his hp needs to be reduced a bit. The mana floor will handicap a bunch of classes even if they play around the mechanic properly.

Archimond doomfire ticks now, but for a bit too much imho.

**Comment by IskrenPlashkov** [comment]
I have been thinking on tuning values and personally am all about on having 1 shot mechanics. This makes fights interesting. However such mechanics need to have some workaround ,else it just turns into frustrating rng fiesta. 

Given the hp values on most t5 geared classes right now I can suggest the mechanics in question - Lich icebolt, Azgalor Rain of Fire etc, to deal about 10k in 4 seconds. This should be enough to 1 shot almost all healers and dps, but also give them enough time to pop cd or get healed. This inlucdes 10k dmg of initial impact + follow up dots.

**Comment by amed80** [comment]
yeah most of my tests were done like 2 weeks ago , didn't see much changes in AC but i guess some stealthy changes were done with random PRs , i guess i need to revisit the raid again 😅

Thanks for the Kaz'rogal response , that's what i was worried about with that boss as i didn't know if it was possible to have enough damage to deal his 13.4M hp in 3:30 (the time it takes for his mark to reach 10sec) and as you said , most mana users will handicap themselves so they don't explode (or melee getting hit with crippling).

For the Icebolt , i think that's one of the spells that should be considered to have the original values instead of tunned one (i think atm it has 130% buff) , also with currently bug as the boss can cast it twice at the same time and on the same target it's hard to see what damage is enough for it.

**Comment by IskrenPlashkov** [comment]
Last night we noticed some weird interactions with D&D. Never seen the double icebolt casts tho but now that MH release has been announce we will do some more small scale tests where I guess this is much more likely to happen.

**Comment by amed80** [comment]
from my testing , after D&D Rage Winterchill will sometimes cast 2 spells instantly, so my guess it has something related with D&D channeling.

**Comment by elthehablo** [comment]
You say fire damage on Archimonde needs nerf, but I also heard people not being damaged by it. What's the deal here?

**Comment by IskrenPlashkov** [comment]
There appears to be inconsistency in taking dmg from the fire debuff. Sometimes it does nothing but when it does dmg it is too much. It is supposed to have highest ticks in the beginning and progressively reducing dmg done.
