### ISSUE TITLE
[PTR Raid report - Tempest Keep]: Solaris

### ISSUE THREAD

**Issue by gavinlfab93** [chromiecraft/PTR-review#2]
### Mechanics comments on trash mobs

bloodwarder marshal the spin damage is to much per tick and range seems to far.
can't kick heals on other trash. Molten armour is being applied to often. 
Phoenix trash wind buffet maybe to much damage is fine but found as melee dps everytime i ran in was getting knocked back again.

### Tuning comments on trash mobs

Hp seems fine, but damage on abilities seem to high on the aoe's, im healing myself alot as a dps to survive.  Phoenix- Hawk range to much on mana burn and to frequent, should only have 30yard range. Crystal core sentinel damage on the overload seems to high 8.9k if not full hp just die, and have to split packs to survive.
Tempest-smith the fragmentation bomb one shots and is suppose to be 2.5-3k damage, maybe 5k for this server, and also the shell shock do same damage and cast almost together.

### Mechanics comments on Al'ar

The jump odwn from top ledge seems like range is to far on ground, jump down and just outside inner circle and still dying.  Meteor needs to be about 1min cd as happening way to often.

### Tuning comments on Al'ar

Flame buffet damage is 3k per tick this seems to much.  Charge damage seems to high just one shots people.

### Tuning comments on Solarian

Arcane missile does to much damage.

### Mechanics comments on Void Reaver

seems fine,

### Tuning comments on Void Reaver

HP could be less tbh just make fight longer. 9mill is good i think.

### Mechanics comments on Kael'thas

Thaladred the darkerner is bugged also runs to fast

### Tuning comments on Kael'thas

The HP seems good on the Kael'thas fight. 

### Overall comments on raid mechanics

Seem quite good in places, some abilities are doing to much damage, as we dont have very big health pool ourselves.

### Give a rating out of 10 for the state of the mechanics in the raid

7

### Overall comments on tuning

Having the mobs with more hp helps with the fact we have higher dps, some mobs seem like they need little bit less hp. TBH i enjoy a bit easier content, actually liked how much hp the mobs had when we first tested, as personally I think more hp just makes fights longer which isn't exactly more enjoyable. 

### Give a rating out of 10 for the state of the tuning in the raid

6

**Comment by gavinlfab93** [comment]
My character is Yamiscourge as part of Solaris.

**Comment by elthehablo** [comment]
Thanks for the report

**Comment by IskrenPlashkov** [comment]
Few more things to add from the same raid:

Al'Ar Meteor is way too frequent - AKA spawns too many adds.
Kael - phoenix egg has only 49k hp. Seems undertuned in comparison to everything else.

**Comment by balleny** [comment]
> Crystal core sentinel damage on the overload seems to high 8.9k if not full hp just die, and have to split packs to survive.

I guess you mean Overcharge? if its only doing 9k damage, then its too low. the ability is supposed to do approx. 14k - 15k damage. https://wowwiki-archive.fandom.com/wiki/Crystalcore_Sentinel

**Comment by gavinlfab93** [comment]
Good day

To clarify it’s doing 9k damage and I’m a dps with 10.4K full buffed, your link says it does 14-15k to main target so the tank with 20k full buffed, and 6k arcane damage to surrounding targets, I mean you link says they usually are split so probably fine as they are.

Sent from my iPhone

On Mar 2, 2024, at 1:28 PM, Balleny ***@***.***> wrote:

﻿

Crystal core sentinel damage on the overload seems to high 8.9k if not full hp just die, and have to split packs to survive.

I guess you mean Overcharge? if its only doing 9k damage, then its too low. the ability is supposed to do approx. 14k - 15k damage. https://wowwiki-archive.fandom.com/wiki/Crystalcore_Sentinel

**Comment by balleny** [comment]
its mostly a matter about being specific because Overcharged Arcane Explosion and Overcharge are to separate abilities

**Comment by gavinlfab93** [comment]
Ok thanks for clarifying, yer I ment the overcharged arcane explosion. Sorry for confusion, still quite new to reporting.

Sent from my iPhone

On Mar 2, 2024, at 3:35 PM, Balleny ***@***.***> wrote:

﻿

its mostly a matter about being specific because Overcharged Arcane Explosion and Overcharge are to separate abilities
