### ISSUE TITLE
[PTR Raid report - The Black Temple]: Solaris - Aug 31st

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/PTR-review#23]
### Mechanics comments on trash mobs

[Aqueous Lord's](https://wotlk.evowow.com/?npc=22878) Geyser sometimes casts his geyser 5+ times. To be investigated further for reason why it happens.
[Illidari Fearbringer](https://wotlk.evowow.com/?npc=22954) [stun ](https://wotlk.evowow.com/?spell=40936)seems to long range. To be investigated further for reason why it happens.
Aggro range on humanoids after supremus too high! (about 40 yards)
[Shadowmoon houndmaster](https://wotlk.evowow.com/?npc=23018) keep patrolling after engaged in combat (only while mounted). Do not move away from tank after they frost nova. To be investigated further for reason why it happens.

Bonechewer Behemoth casts both his abilities twice.  - BUG
Bonechewer Brawler is not linked to nearby packs.  - BUG

RoS gauntlet adds do not respawn  - BUG

### Tuning comments on trash mobs

Overall tuning on spell dmg is a too high, particularly on :
[Aqueous spawn's](https://wotlk.evowow.com/?npc=22883) [sludge nova](https://wotlk.evowow.com/?spell=40102) does too much dmg.
[Aqueous Lord's](https://wotlk.evowow.com/?npc=22878) Geyser hits multiple times for about 2.5k frost dmg.
[Shadowmoon Champions](https://wotlk.evowow.com/?npc=22880) [Whirling Blade](https://wotlk.evowow.com/?spell=41053) does too much dmg 10k ish.

### Mechanics comments on High Warlord Najentus

All abilities working fine.

### Tuning comments on High Warlord Najentus

Seems bit easy. Then again he was quite easy on retail so should be fine.

### Mechanics comments on Supremus

Molten Flames does its dmg multiple times per second. Very similar to how doomfire used to be initially. - BUG
Molten flame still moves in random directions instead of a straight line. - BUG

### Tuning comments on Supremus

Volcano dmg is **way too high**. Right now even if u move as soon as it spawn animation is played u still die. Needs to be nerfed by at least 50%.

### Mechanics comments on Shade of Akama

Akama receives healing from judgement of light, making him practically immortal.

### Tuning comments on Shade of Akama

Mob hp seems a bit high actually and is easy for casual groups to get overwhelmed. 

### Mechanics comments on Teron Gorefiend

Shadowy constructs are too fast. - Not much of an issue but not blizzlike. Feel free to keep the way they are if u want to incrase difficuty.

### Tuning comments on Teron Gorefiend

Dmg and hp seem fine, In fact fight is a bit boring.

### Mechanics comments on Gurtogg Bloodboil

Boss keeps casting Bloodboil in phase 2 - BUG
If fixate targets uses divine shield the boss keeps attacking them - BUG

### Tuning comments on Gurtogg Bloodboil

The fight is very intensive for healers but this is by design. Will likely by too difficult for casual groups but we need to test again once the bloodboil cast in p2 bug is fixed. This really adds a whole new dimension of difficulty to the fight.

### Mechanics comments on Reliquary of Souls

Bandages work in phase 1  - BUG

### Tuning comments on Reliquary of Souls

Essence of suffering - Looks good. If anything hp can be increased to match Essence of Anger.
Essence of Desire - literally unkillable right now. Even if no1 kills themselves from reflected dmg the boss hp is high enough that people eventually go to 0 mana and thus wipe. I suggest nerfing boss hp in this phase by at least 50% and then see how it goes.
Essence of Anger - HP actually seems great and the soft enrage mechanic feels hard enough.
Essence of Anger - Spite end up doing about 10 dmg which is or close to 1 shot. Even if the player survives it it will surely die to the next aura of anger tick. Might want to nerf the Spite dmg to not make this 1 shot mechanic.

### Mechanics comments on Mother Shahraz

Fatal attraction teleports 2 of the players to the third one's location. All 3 should teleport to the middle of the room - BUG
Fatal attaction does its 3k dmg multiple times in the same tick - does over 100k dmg in a single second. To be investigated further for reason why it happens.
Fatal attraction chains appear again and start doing dmg if players get close to each other after initially breaking them. - BUG

### Tuning comments on Mother Shahraz

Her shadow dmg is very difficult to judge right now due to the many bugs with Fatal Attraction. Need to be tested again once they are fixed.

### Mechanics comments on The Illidari Council

They do not share HP - BUG
They only drop 1 item in total - BUG

### Tuning comments on The Illidari Council

HP and dmg tuning seems perfect. Do not touch it.

### Mechanics comments on Illidan Stormrage

The 2 fire elementals in p2 spawned enraged and wire lightning fast. To be investigated further for reason why it happens.

### Tuning comments on Illidan Stormrage

HIs AA and parasitic shadowfiend debuff (initial cast) might need small nerf - about 10%.

### Overall comments on raid mechanics

Actually seems a bit more broken than the last time we tested before the tuning. Also doesnt help that after the first wipe we got locked out of illidan.
We will go back tomorrow to retest some more niche and less impactful boss mechanics to make sure nothing slipped through the cracks.

### Give a rating out of 10 for the state of the mechanics in the raid

5

### Overall comments on tuning

Trash HP seems adequate.
Certain trash spells feel overtuned. Needs more triage. 
Boss tuning is mostly fine with some notable exceptions.

### Give a rating out of 10 for the state of the tuning in the raid

4

**Comment by heyitsbench** [comment]
Please report the bugs in the [CC issues page](https://github.com/chromiecraft/chromiecraft/issues).

**Comment by IskrenPlashkov** [comment]
Why is it no longer enough to raise them here ?

**Comment by heyitsbench** [comment]
> Why is it no longer enough to raise them here ?

As far as I'm concerned, it was never enough just to raise them here.

**Comment by elthehablo** [comment]
Bugs can be raised here, and we're happy that we get extra attention to them here, however what Bench said is true. If bugs are new and not reported, please report them in the issues section.

**Comment by Nyeriah** [comment]
Unfortunatelly issues need to be reported so they can get properly triaged and also so they're visible to other contributors who may not be in tune with Chromiecraft.

**Comment by IskrenPlashkov** [comment]
Alright, I see. As most of the bugs reported here have been addressed already I will make a new reporting following our PTR test tonight. New bug reports will also be created for the issues persisting.
