### ISSUE TITLE
[PTR Raid report - The Black Temple]: Solaris SEP 7TH

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/PTR-review#24]
### Mechanics comments on trash mobs

[Aqueous Lord's](https://wotlk.evowow.com/?npc=22878) Geyser sometimes casts his geyser 5+ times. To be investigated further for reason why it happens.
[Illidari Fearbringer](https://wotlk.evowow.com/?npc=22954) [stun ](https://wotlk.evowow.com/?spell=40936)seems to long range. To be investigated further for reason why it happens.
Aggro range on humanoids after supremus too high! (about 40 yards). Especially on the fell hunters.
[Shadowmoon houndmaster](https://wotlk.evowow.com/?npc=23018) keep patrolling after engaged in combat (only while mounted). Do not move away from tank after they frost nova. To be investigated further for reason why it happens.
[Bonechewer Behemoth](https://wotlk.evowow.com/?npc=23196) casts both his abilities twice. - BUG
[Bonechewer Combatant](https://wotlk.evowow.com/?npc=23239) and [Bonechewer Brawler](https://wotlk.evowow.com/?npc=23222) are not linked to the spectator packs nearby. - BUG

### Tuning comments on trash mobs

Overall tuning on spell dmg is a too high, particularly on :
[Aqueous spawn's](https://wotlk.evowow.com/?npc=22883) [sludge nova](https://wotlk.evowow.com/?spell=40102) does too much dmg. 3k per sludge nova. This is extremely lethal on the big pack imemdiatelly after 1st boss. When there is only 2 mobs in a patrol this is manageable.
[Aqueous Lord's](https://wotlk.evowow.com/?npc=22878) Geyser hits multiple times for about 2.5k frost dmg.
[Shadowmoon Champions](https://wotlk.evowow.com/?npc=22880) [Whirling Blade](https://wotlk.evowow.com/?spell=41053) does too much dmg 10k ish.

### Mechanics comments on High Warlord Najentus

All abilities working fine.

### Tuning comments on High Warlord Najentus

Seems bit easy. Then again he was quite easy on retail so should be fine.

### Mechanics comments on Supremus

Molten Flames does its dmg multiple times per second. Very similar to how doomfire used to be initially. - BUG
Molten flame still moves in random directions instead of a straight line. - BUG

### Tuning comments on Supremus

Volcano dmg is way too high. Right now it does 5k+ every hit (it does multiple hits per second - guaranteed 1 shot).

### Mechanics comments on Shade of Akama

All abilities working fine.

### Tuning comments on Shade of Akama

Mob hp seems a bit high actually and is easy for casual groups to get overwhelmed. Needs to be retested again with proper 25 man raid team.

### Mechanics comments on Teron Gorefiend

It is possible to shadowmeld while shadow of death is being cast on you. The player does not get the debuff and survives but the shadowy constructs spawn immediately. Is this considered a BUG ?

### Tuning comments on Teron Gorefiend

Seems pretty good actually.

### Mechanics comments on Gurtogg Bloodboil

They all appear to be working correctly right now.

### Tuning comments on Gurtogg Bloodboil

He is doing too much dmg in phase 2. Even a rogue with evasion barely survives. Needs 20% dmg done nerf in P2 I believe.

### Mechanics comments on Reliquary of Souls

The proxy agro in phase 1 seems to be done in 3-4 seconds interval. AKA it is possible to talk between the boss and the tank and not get aggro.  Also if you end up with aggro it is not enough for the tank to just go between you. He has to go between you and stay there for up to 3-4 seconds when the next proximity aggro check happens. - IS this intentional is it wasnt the case before ?

### Tuning comments on Reliquary of Souls

Essence of suffering - Looks good. If anything hp can be increased to match Essence of Anger.
Essence of Desire - literally unkillable right now. Even if no1 kills themselves from reflected dmg the boss hp is high enough that people eventually go to 0 mana and thus wipe. I suggest nerfing boss hp in this phase by at least 50% and then see how it goes.
Essence of Anger - HP actually seems great and the soft enrage mechanic feels hard enough.
Essence of Anger - Spite end up doing about 10 dmg which is or close to 1 shot. Even if the player survives it it will surely die to the next aura of anger tick. Might want to nerf the Spite dmg to not make this 1 shot mechanic.

### Mechanics comments on Mother Shahraz

Fatal attraction teleport now works, however sometimes people get teleported into a corner, making separating fast enough impossible. - BUG
Fatal attraction does its 3k dmg multiple times in the same tick - does over 50k dmg in a single second. - BUG\
Fatal attraction chains appear again and start doing dmg if players get close to each other after initially breaking them. - BUG

### Tuning comments on Mother Shahraz

Her shadow dmg is very difficult to judge right now due to the many bugs with Fatal Attraction. Need to be tested again once they are fixed.

### Mechanics comments on The Illidari Council

Their hp is still not shared and they remain on 1 hp. - BUG

### Tuning comments on The Illidari Council

Tuning seems to be great actually.

### Mechanics comments on Illidan Stormrage

Shadowfiends can sometimes target the person they were spawned from - BUG
P2 fire elementals enrage on spawn and also move way too fast. - BUG
Demon fire does its dmg 4 times per second.- BUG
There appears to be an issue with p2 to p3 transition. This will be investigated further but might lead to some false positive bugs in the next phases.
Shadow Demons do not move towards their target - BUG (its possible that this is caused by buggy transitions from p2 to p3)

### Tuning comments on Illidan Stormrage

His AA is still too high.
P2 elemental dmg is way too high, even before enrage.
Phase 4 shadowbolt dmg might need small 10% dmg nerf.

### Overall comments on raid mechanics

6 Bosses seems to be scripted more or less fine. Mother and Ros have some bugs but Illidan is quite buggy indeed. Deff needs more testing on this guy.

### Give a rating out of 10 for the state of the mechanics in the raid

6

### Overall comments on tuning

Trash HP seems adequate.
Certain trash spells feel overtuned.
Boss tuning is mostly fine with some notable exceptions. RoS essence of desire needs HP nerf badly. Supremus volcanoe dmg needs to be hit by the nerf hammer too. Illidan and Bloodboil need 10-15% AA dmg nerf.

### Give a rating out of 10 for the state of the tuning in the raid

6

**Comment by heyitsbench** [comment]
> Molten Flames does its dmg multiple times per second. Very similar to how doomfire used to be initially. - BUG

This should have been fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/cdd816a1c6469b125998cfe55e3529e9f85a15b2.

**Comment by IskrenPlashkov** [comment]
Will be creating git issues for the remaining bugs soon.
