### ISSUE TITLE
[PTR Raid report - The Black Temple]: ZUG ZUG group of various guilds.

### ISSUE THREAD

**Issue by HasieEST** [chromiecraft/PTR-review#26]
### Mechanics comments on trash mobs

- **Aqueous Spawns** can be stunned, banished, interputed, thus allowing players to disable merge mechanic, which shouldn't be the case.
- **Dragonmaw Sky Stalker** immolation arrow gfx is mismatched. Uses Hunter Explosive trap gfx instead of burning patch gfx *used by archers in Shattered Halls Gauntlet* . Mainly a clarity issue.
- **Dragonmaw Wyrmcaller** doesn't seem to fixate on random enemy.
- **Illidari Hearseeker** doesn't seem to use Curse of Agony nor Skeleton Shot
- **Shadowmoon Deathshaper** doesn't seem to be using Death Coil nor spawning Skeletons off of near corpse
- **Shadowmoon Weapon Master** doesn't correctly swap auras (can stack all of available auras with one of the auras being a buff, rest being a debuff)
- **Wrathbone Flayer** doesn't seem to use Ignored spell. (Shouldn't be shacklable, haven't tested shackling it.)
- **Bonechewer Behemoth** AoE Fel Stomp isn't affecting proper range (should be up to 15 yrds instead of below 10yrds)
- **Bonechewer Blood Prophet** might not use Prophecy of Blood on any targets.
- **Bonechewer Blade Fury** might not use Whirlwind and thus not resetting aggro
- **Soul fragments** during Gauntlet to RoS do not have quick respawn timer, thus not requiring a reclear if players wipe. Should have quick respawn until RoS is defeated.
- **Mistress of Dementia** doesn't seem to spawn **Image of Dementia**'s thus no little ghost girl that whirlwinds around for few seconds.

## **Disclaimer: Comments on tuning is from personal opinion and may not represent entire group's view. This is applicable here and any other comment box, which asks to give comments on tuning.**

Overall trash is tuned within reasonability. I personally think that majority of the trash is tuned finely ( *easy to do when properly pulled, easily overwhelming, if done incorrectly*) .

- **Bonechewer Weaponmaster** could use a slightly higher HP pool to allow it to have a bit of time to use at least 2 - 3 auras (pack that accompanies it is relatively weak and dies easily to AoE without CC)
- **Promenade Sentinel** L5 Arcane Charge could be modified to represent the spirit of the ability back in TBC (or it's classic release). During TBC L5 AC did 100% of target's maximum HP, thus requiring target to be fully healed and shielded. With wrath talents we have access to blanket -3% dmg reduction via Disc Priest or Prot Paladin's Blessing of Sanctuary. 

### Mechanics comments on High Warlord Najentus

As it Stands, High Warlord Najentus is written properly and doesn't seem to have any mechanical issues. 

### Tuning comments on High Warlord Najentus

Needle Spine damage is ignorable currently and Tidal Shield dmg with some passive Frost resist aura isn't threatening, when combining it with unfortunate timing of Needle Spine. 

**As it stands, if tuning is kept as it is, then nothing is lost and nothing is gained.**

### Mechanics comments on Supremus

- **Supremus** doesn't currently get a movement speed boost, if player is too far away from the mob.
- **Molten Flame** currently doesn't chase player, instead moving at a straight line. It's blizzlike behavior should be to crawl towards a random player for half of its duration then linger for along the traveled path for 2nd half of it's duration. 
- **Fixate** currently doesn't seem to always hit the target with damage and then knock him back. 

### Tuning comments on Supremus

Overall tuning is good. Volcanos and Molten Flames are proper threat that raid groups should play around to avoid a wipe. It's health pool and damage output without abilities is fine and allows for decent clear times within reasonable gameplay expertise expectation. 

### Mechanics comments on Shade of Akama

- **Ashtongue Sorcerers** can be CC to interput their channel which shouldnt be the case
# **Didn't test, there for needs a proper check**
Shade of Akama should not be able to move if he has any number of channelers on him or 4+Sorcerers on him. [Link to observed behaviour](https://www.youtube.com/watch?v=JSQWdhaj498)

### Tuning comments on Shade of Akama

Tuning wise seems okay. Due to split dmg group, we could easily manage sorcerers count but in return we didn't really have any issues clearing channelers either. Perhaps raising Channelers health a bit to make splitting damagers between incoming adds and rushing Channelers bit more punishing timewise compared to rushing Channelers down first. Especially since if you manage to get to Phase 2, its a essentially a glorified target dummy portion of the fight.

### Mechanics comments on Teron Gorefiend

Constructs that spawn on the area marked with skulls can some times bug out and be stuck at their spawned location. *Refer to image below*

![image](https://github.com/user-attachments/assets/fc7a39af-e5de-46b9-bfd1-358c10ffe19b)

### Tuning comments on Teron Gorefiend

Tuning here is reasonable. All of Teron's abilities are tuned where if you don't heal or dispel dot from incinerate, targeted player would die but be manageable if you either heal or dispel the dot. 

### Mechanics comments on Gurtogg Bloodboil

Mechanics seems to be functioning as intended. During Fel Rage phase, couldn't properly test those abilites, so wont comment on it.

### Tuning comments on Gurtogg Bloodboil

N/A due to using .damage command and not retrying boss. 

### Mechanics comments on Reliquary of Souls

Mechanics seems to be working as intended. 

### Tuning comments on Reliquary of Souls

Phase 1 Fine, Phase 2 could use a bit of forgiveness, as increased HP pool directly cuts down on healers's uptime % and damage dealer's self-induced damage is a bit too high comparatively speaking due to increased dmg output that isn't scaled up proportionally with their increase in health pools. Phase 3 Seems fine enough.
Had to use commands to test phase 3.

### Mechanics comments on Mother Shahraz

Fatal attractions seems to be ticking every half a second instead of each second. Thus making it a lot more punishing.

### Tuning comments on Mother Shahraz

With current tuning, it can be done without Shadow Resistance in theory (thus making it a burn boss before everybody die to Fatal attraction). 

### Mechanics comments on The Illidari Council

Mechanically speaking seems fine. No outlying issues with any of the council member spells noticed.

### Tuning comments on The Illidari Council

N/A due to time constraints and commands used.

### Mechanics comments on Illidan Stormrage

Illidan seems good phase 1 and Phase 2. Cant comment on Flames of Azzinoth due to 1 try and no real benchmarks. 
Illidan doesn't currently reset threat after phase 2 and between Demon and Humanoid form, which shouldnt be the case.
Phase 4 cant be commented due to 1 try and time limitations.

### Tuning comments on Illidan Stormrage

N/A due to time constraints and commands used.

### Overall comments on raid mechanics

As it stands, Most of the bosses are written to be using their abilities. 

### Give a rating out of 10 for the state of the mechanics in the raid

7

### Overall comments on tuning

For the most part, tuning is hitting the sweet spot, where doing pulls and mechanics correctly makes trash easy and improperly pulled trash harder. Bosses for the most part are tuned within reasonability, with exception of Phase 2 RoS. 

### Give a rating out of 10 for the state of the tuning in the raid

7

**Comment by Belodina** [comment]
Thank you Hasie!

Link to video of the run: https://youtu.be/5KAWBjSvIl0?si=w3S6jYZn5nGXOREF

**Comment by elthehablo** [comment]
Thanks for the review. If you would be so kind to provide us with a screenshot of the players involved so we can hand out some rewards :)

**Comment by HasieEST** [comment]
> Thanks for the review. If you would be so kind to provide us with a screenshot of the players involved so we can hand out some rewards :)

I believe that riddian (GM of Horizon) has submitted request ticket for rewards for it via Discord channel, thanks to BEEF's suggestion. For more information, please refer to mentioned ticket, that should be CC discord ticket system, either as open ticket or already solved ticket.
