### ISSUE TITLE
[PTR Raid report - Tempest Keep]: Limbo - NA Team

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/PTR-review#3]
### Mechanics comments on trash mobs

Thrash seems to be doing all mechanics from what we could gather.
- Phoenix-Hawk: Mana Burn hits 4 times instead of one, hitting all mana users for more than 12k which is a one shot all casters, it also hits through walls. https://github.com/chromiecraft/chromiecraft/issues/6744
- Nether Scryers: They are casting Dominate in the whole raid instead of a single target, effectively mind controlling the whole raid. https://github.com/chromiecraft/chromiecraft/issues/6748

### Tuning comments on trash mobs

The tuning on trash feels quite different from SSC as you need to CC some of enemies as spells/abilities can just one-shot people like Heroic Dungeons on release last year.

These mobs are not broken, work as in TBC and require coordination unlike current SSC
- Bloodwarder Marshal: 1 shots melee 
- Crimson Hand Centurion: they hit hard and have to be poly-spammed like the axe-throwers in ZG 

### Mechanics comments on Al'ar

- Flame Quills hits people outside the ramp: 
https://youtu.be/Y8cMTH3vIng?si=bv66H_u_qEfaS7Zy&t=1777
https://github.com/chromiecraft/chromiecraft/issues/6746

- Alar disappeared after Phase 1, there was no Phase 2 https://github.com/chromiecraft/chromiecraft/issues/6798

### Tuning comments on Al'ar

- Adds have a lot of health which makes mathematically not worth killing because they only remove 2% health from the boss, it might need some checking depending on how you want this fight to be done. As it stands is better to ignore the adds and focus on the boss.
- Overall, difficult to comment any more on it without seeing the whole fight.

### Mechanics comments on Solarian

- Solarium Agents have too much health, we went in with a full team that clears SSC without wipes in under 2 hours, but we couldn't clear the adds before the boss spawned with priests. You should consider that the adds need to be dead in less than 15 secs by a normal team of players.
- **Solarium Reinforcements:** Solarian disappears but has a delay with the summons giving even less time to kill adds, effectively around 11-12 secs.

### Tuning comments on Solarian

- Solarian Agents have too much health and can't be killed in less than 15 secs which creates a problem with adds adding up over other adds.
- Arcane Missiles hit 3 times for over 4k each hit, killing anyone who doesn't get immediately healed before the channel is finished. The normal 3k dmg would be more reasonable with the amounts of health people have with our current geared. https://wowpedia.fandom.com/wiki/High_Astromancer_Solarian

### Mechanics comments on Void Reaver

The fight seemed ok.

### Tuning comments on Void Reaver

Seems OK for a full geared T5 Best in Slot team.

### Mechanics comments on Kael'thas

- Thaladred the Darkener runs faster than any melee, it should run slower. https://github.com/chromiecraft/chromiecraft/issues/6657
- We wiped and the fight didn't reset correctly
- We never got to P3 as the advisors never resurrected and Kael'thas became targeatable
- Dagger did not remove Mind Control https://github.com/chromiecraft/chromiecraft/issues/6665

### Tuning comments on Kael'thas

- Master Engineer Telonicus is one shooting people on the bombs with 13k dmg, that is not supposed to happen
- Grand Astromancer Capernian Fireball, Arcane Burst and  Conflagration damage is around 15% or more higher than it should based on https://wowpedia.fandom.com/wiki/Kael%27thas_Sunstrider_(tactics)

### Overall comments on raid mechanics

At the point of this test, only 1 out of 4 bosses was doable. 2 bosses had broken scripts on Phase transitions (Alar and Kael'thas) and with Solarian spawning adds too fast and overwhelming the raid.

For rating, if we put 2 points for each boss and 2 points for the trash for a total of 10 points. With only Void Reaver being fine, Solarian needing just some minor adjustments and trash being mostly OK, except for Phoenix-Hawks and Nether Scryers, we can rate it with a 5 out of 10.

### Give a rating out of 10 for the state of the mechanics in the raid

5

### Overall comments on tuning

Hard to comment on the tuning because there is no official statement on what is the idea or for whom these raids are directed too. Also 50% of the bosses bugged out in Phase transitions so it's hard to rate them when we couldn't see the whole fight. In comparison with SSC:
- It seems more time consuming with trash needing lots of Crowd Control
- Alar might need to be checked depending on how you want the raid to clear the boss
- Solarian needs the health of the adds checked and Arcane Missiles doing normal 3k dmg instead of 4.2k is doing atm.
- Kaelthas adds might need some checking on damage they inflict (Telonicus, Capernian)

### Give a rating out of 10 for the state of the tuning in the raid

5

**Comment by elthehablo** [comment]
Thanks for the report
