### ISSUE TITLE
[PTR Raid report - Tempest Keep]: Limbo - EU Team

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/PTR-review#7]
### Mechanics comments on trash mobs

**Critical Issue**
- Nether Scryers: They are casting Dominate in the whole raid instead of a single target, effectively mind controlling the whole raid. While reported as completed, this was not working on the PTR as of March 10th https://github.com/chromiecraft/chromiecraft/issues/6748 as shown in the footage here: https://youtu.be/E3Lz1Zx3lPw?si=GKRSBiY_XqYE6ZAD&t=5566, notice how they reset after everyone got mind controlled.

**Normal Issues**
- Tempest Falconers just stand up there https://github.com/chromiecraft/chromiecraft/issues/6824
- Astromancer Lord doesn't use domination https://github.com/chromiecraft/chromiecraft/issues/6781
- Crystalcore Devastators not working as intended. https://github.com/chromiecraft/chromiecraft/issues/6765 https://youtu.be/kSt8VJxral0?si=She5BXRKuhfjV9IN&t=2543 
- Phoenix-Hawk does not use it's Dive ability. The issue has been closed a couple of times now but not fixed. https://github.com/chromiecraft/chromiecraft/issues/6654 https://github.com/chromiecraft/chromiecraft/issues/6521

**Confirmed Fixed issues:**
- Phoenix-Hawk: Mana Burn hits 4 times instead of one https://github.com/chromiecraft/chromiecraft/issues/6744

### Tuning comments on trash mobs

- Once you identify which trash mobs need Crowd Control and how to position them, it makes it quite easier to clear each pack. It's definitely quite harder than anything in SSC and might present a problem for unprepared PUGs.

### Mechanics comments on Al'ar

**Critical Issue**
- Al'ar not transitioning to Phase 2: https://github.com/chromiecraft/chromiecraft/issues/6798 this is a huge issue, in 4 tries with a full 25m we have been unable to have it transition to Phase 2. The target seems to die and but not disappear, not triggering the Rebirth spell, if you do it with GM damage commands this doesn't happen which makes me believe there is damage threshold that is not being beaten.

**Footage of this last run**
- Dies while doing Flame Quill, doesn't transition https://youtu.be/E3Lz1Zx3lPw?si=pEWHdR2Rh1dfS83a&t=2287 
- We wait for it to land this time but still bugs out https://youtu.be/E3Lz1Zx3lPw?si=XlOAtQdyfQe8ueAu&t=2813 

**Normal Issues**
- Alar disappeared after Phase 1, there was no Phase 2 https://github.com/chromiecraft/chromiecraft/issues/6798
- Al'ar's Divebomb Is Spread Damage https://github.com/chromiecraft/chromiecraft/issues/6644
- Killing adds not dealing damage to Al'ar https://github.com/chromiecraft/chromiecraft/issues/6637

**Confirmed Fixed Issues**
- Flame Quill seems to be working OK now https://github.com/chromiecraft/chromiecraft/issues/6726 https://github.com/chromiecraft/chromiecraft/issues/6746
- Dive Bomb seemed to happen normally and not spammed https://github.com/chromiecraft/chromiecraft/issues/6750

### Tuning comments on Al'ar

- The fight seems OK if you correctly deal with the mechanics as they are. Should be clearable by any PUG.

### Mechanics comments on Solarian

- Big issue here. If not fixed, raids will have to stop DPS to avoid getting the transition while the boss is phased out. https://github.com/chromiecraft/chromiecraft/issues/6840
- Wrath of the Astromancer's damage is too high can can be critical, effectively killing players with a 1 shot. This should be survivable if the player is correctly doing the mechanic. https://github.com/chromiecraft/chromiecraft/issues/6784

### Tuning comments on Solarian

Adds have too much health. While clearable by organized guilds, this fight as it is will be a problem for PUGs if they can't deal with the DPS checks. Here is a video of 2008 from OG TBC that shows that even back then with way less AoE power, adds were dying much quicker than in CC https://youtu.be/6ST3lNSc0Xc?si=5DHHdsq_bShkjCdx&t=44

### Mechanics comments on Void Reaver

- Everything seems to be working as intended.

### Tuning comments on Void Reaver

- The fight seems OK if you correctly deal with the mechanics as they are. Should be clearable by any PUG.

### Mechanics comments on Kael'thas

**Critical Issues**
- Infinity Blade not clearing MC reliably. This doesn't seem to be fixed on the PTR, which makes Phase 4 really difficult to deal with. https://github.com/chromiecraft/chromiecraft/issues/6665
- Staff of Disintegration not working correctly https://github.com/chromiecraft/chromiecraft/issues/6810
-  Lord Sanguinar casts Bellowing Roar too often, preventing melee to do reliable damage https://github.com/chromiecraft/chromiecraft/issues/6839
- Telonicus bomb range is too large and hits too hard, preventing melee to do any damage https://github.com/chromiecraft/chromiecraft/issues/6661
- Thaladred the Darkener's speed is too high https://github.com/chromiecraft/chromiecraft/issues/6657

**Normal Issues**

- Netherstrand Longbow not always lootable https://github.com/chromiecraft/chromiecraft/issues/6796
- Kael'thas moves in Phase 5 https://github.com/chromiecraft/chromiecraft/issues/6837
- Kael'thas Gravity Lapse should summon players close to Kael beforehand https://github.com/chromiecraft/chromiecraft/issues/6686
- Kael'thas Phoenix movement speed too high, but since it can be slowed now this might not be an issue anymore https://github.com/chromiecraft/chromiecraft/issues/6684
- Kael'Thas P2 weapon items remain in inventory after reset https://github.com/chromiecraft/chromiecraft/issues/6782
- Kael'thas weapons spawn as unattackable. https://github.com/chromiecraft/chromiecraft/issues/6792
- Advisors start on half HP on Phase 3 https://github.com/chromiecraft/chromiecraft/issues/6714
- Thaladred the Darkener's script seems to have it's scripting borked when he hits somebody and there is more people o the raid https://github.com/chromiecraft/chromiecraft/issues/6542

**Confirmed Fixed issues:**
- It's resetting properly now https://github.com/chromiecraft/chromiecraft/issues/6599
- Seems to be flying during the RP transition from P3 to P4 normally https://github.com/chromiecraft/chromiecraft/issues/6601

### Tuning comments on Kael'thas

Kael'thas is the only fight that seems to be off and if things are not fixed, it will require a perfect execution to have a chance of clearing.

**Phase 1:**
- Grand Astromancer Capernian: Damage is higher than it should because of the increased global damage. Still doable with a specialized character that can soak the damage, but this decreases raid DPS.
- Thaladred the Darkener runs too fast, making it impossible to outrun if you are caught in a bad position.
- Lord Sanguinar fear is casted every 14 seconds instead than 30.
- Master Engineer Telonicus Bombs are hitting for 10-13k+, double the damage that they should be inflicting 7-9k effectively one shotting any melee that is not a tank, also you can't ourhttps://wowpedia.fandom.com/wiki/

**Phase 2**
- Weapons have as much health as the advisors, they should have a third of their help https://wowpedia.fandom.com/wiki/Kael%27thas_Sunstrider_(tactics) 
- Many weapons are not working correctly
- The Bow depending on where it dies becomes unlootable
 
**Phase 3**
- This one is especially harder since there are many problems associated with all the advisors. The fact that Lord Sanguinar fears constantly, Telonicus hits for 16K+, Thaladred runs faster than players and Capernian being a range only fight, makes any melee useless on this phase as they can't do any damage to anything.

**Phase 4**
- The Mind Control and the Dagger not dispelling the debuff correctly makes this part much harder than it should. As it stands, if you don't have enough CC to not kill your team mates, you will start losing a lot of people and potentially wipe.

**Phase 5**
- Seems all right if you can make it here. Still some problems like the boss moving around and people being able to be on the ground.

### Overall comments on raid mechanics

At the point of this test, only 2 out of 4 bosses were doable.
- Al'ar never switched to Phase 2 correctly in all of our 4 attempts.
- Nether Scryers casting dominate on the whole raid will make killing Solarian impossible if you can't clear the trash as it's linked.
- Kael'thas has too many problems that make the fight unnecessary hard and unpredictable, might not be clearable on release if bugs persist.

### Give a rating out of 10 for the state of the mechanics in the raid

5

### Overall comments on tuning

- In general, Al'ar and Void Reaver seem doable by PUGs. Solarian has a high DPS check regarding the adds which might make it hard on PUGs. Kael'thas weapons have too much health, Telonicus one shots any melee. Damage in general seems OK, but dealing with the Mind Controls it's a huge problem at the moment that will make it very hard for any group to clear this boss on release.

### Give a rating out of 10 for the state of the tuning in the raid

5

**Comment by elthehablo** [comment]
Thanks for the report
