### ISSUE TITLE
[PTR Raid report - Mount Hyjal]: Solaris 13th April

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/PTR-review#9]
### Mechanics comments on trash mobs

**Ghoul:**

- Frenzy - works
- Canibalize - works

**Crypt fiend:**

- Web - does not work - **BUG**

**Abomination:**

- Disease cloud - works
- Knockdown - works

**Shadowy Necromancer:**

- Shadow bolt - works
- Cripple - works
- Summon Skeletons - Currently summon both melee and ranged add at the same time. I believe it is supposed to be one or the other. Possible bug.
- Unholy Frenzy - works
- Once MC he cant use any abilities. He should be able to cast Unholy Frenzy to allies. - **BUG**

**Banshee**

- Bashee Wail - works
- Anti-magic shell - works

**Gargoyle**

- Gargoyle strike - works

**Frost Wyrm**

- Frost Breath - works

**Giant Infernal**

- Stun on impact - works
- Immolation - works
- Flame Buffet - does not work - **BUG**

**Fel Stalker**

- Mana burn - works

### Tuning comments on trash mobs

Ghoul - Bit weak but fine.
Crypt Fiend - Bit weak but fine.
Abomination - 2nd highest threat trash. 5k aoe per tick per mob is quite strong, so they got the be separated quickly.
Shadowy Necromancer - By far the most dangerous trash. Shadow bolt dmg is fine but if all focus a  healer its a kill. They also very quickly summon more adds. The melee are a joke but casters can also very quickly nuke a healer or ranged dps.
Banshee - piss easy
Gargoyle - Very annoying to deal with. Take forever to get into range and only ranged can deal with them. Only danger is if they all focus a healer but overall quite weak otherwise.
Frost Wyrm - They are ok. Will be bit problematic to deal with for melee heavy comps as they got 1m hp but overall fine.
Giant Infernal - They are ok as they are.
Fel Stalkers - Bit weak but fine.

### Mechanics comments on Rage Winterchill

Frost Armor - nowhere to be seen - **BUG**
Death and Decay - Works
Icebolt - Works
Frost Nova - Works

### Tuning comments on Rage Winterchill

Nova dmg bit Strong. Could be lethal if comboed with D&D but keeps the priests on their toes. Personally I like both.
Iceblolt is way too strong and absolutely needs a **nerf**. The initial dmg is 7.75 to 8k dmg, **immediately** followed by 3.750 dmg. This causes over 11.5k dmg instantly. Unlike Solarian where 12k dmg is done over 2 seconds, but crutially in TK we have a warning who the target is going to be. Here he just picks a random person who unless randomly shielded or tank just dies.

### Mechanics comments on Anetheron

All abilities work fine.

### Tuning comments on Anetheron

Infernal is a bit too strong. Immolate aura high dmg prevents melees from dpsing them. AA too strong too - not a problem for tanks but any dps or healers initially taking aggro can easily die. Currently u cant afford to stack too many of them, so ranged are forced to kill them. For melee heavy comps this will be a problem.

Maybe a small overall nerf to their hp and dmg will be good to not cock block more casual guilds.

### Mechanics comments on Kaz'rogal

Cripple - works
War stomp - works
Malevolent cleave - works
Mark of Kaz'rogal - 
Does not target all mana users - **BUG**
When players go oom from debuff they do not explode - **BUG**

He should also be tauntable from the sources I have seen - **BUG**

### Tuning comments on Kaz'rogal

His AA dmg makes pala tanking possible even with mana drain debuff.
Cleave very strong but keeps melee on their goes.
His overall hp might be difficult to judge atm as mark doesnt kill people. If ppl actually have to watch out for mana dmg output will be lower and this will work as soft enrage. Will need further testing once mark explosion dmg is fixed.

### Mechanics comments on Azgalor

Cleave - works
Rain of Fire - works
Howl of Azgalor - works
Doom - Works

### Tuning comments on Azgalor

Doomguards might be a bit too strong. Need to be retested again once rain of fire dmg is nerfed.
Rain of fire - This needs a massive **nerf**. Aoe area is big so lots of players hit every time. First hit is 2.6k followed by 5 ticks of 1875. This causes 12.5k dmg to a big portion of the raid on regular basis, and that is assuming everyone moves away before 2nd tick. Neither healers nor overall hp is strong enough for such numbers right now.

### Mechanics comments on Archimonde

Air Burst and Tears of the goddess both work fine
Fear - works
Grip of the legion - works
Doomfire Strike - Targeting random player works, however the fire moves in a very weird pattern (from videos I have seen it should be more staggered - atm its very fluid and catches up to players quickly). Animation seems to fast. Also does no dmg at all - **BUG**
Finger of death triggers very quickly into the fight, insta killing everyone. Not sure what is triggering it at this point, making any testing very difficult.
Soul Charge - cant really be tested atm as finger of death kills everyone.

### Tuning comments on Archimonde

Fight is very bugged right now. Once finger of death is fixed we will be able to figure out how soul charges work.

### Overall comments on raid mechanics

Other than Archimonde most boss mechanics works fine. The big exception is the mark of kazrogal.

Few trash mechanics missing but not too much of an issue there.

### Give a rating out of 10 for the state of the mechanics in the raid

7

### Overall comments on tuning

Trash is actually interesting to deal with. Shadowy Necromancers are a bit strong right now, need coordinated focusing and CC. Abominations are quite strong also, but nothing even the more casual raids cant deal with. Flying adds in horde camp are annoying but that is how they always were.

Boss hp might be changed here and there. Not much point in having first 4 bosses having the same hp but not a deal breaker either. All bosses basic attacks do good dmg and we dont feel they need changing.

### Give a rating out of 10 for the state of the tuning in the raid

8

**Comment by amed80** [comment]
> Crypt fiend:
> Web - does not work - BUG

After watching multiple videos and looking at multiple logs , i do believe this spell is a myth even when guides are mentioning it.
there is only one video where it was used which make me guess the video was from either pserver or maybe PTR version? because everything else even solo runs they never used this spell.

> Shadowy Necromancer:
> Summon Skeletons - Currently summon both melee and ranged add at the same time. I believe it is supposed to be one or the other. Possible bug.

this is not a bug , Necro have 3 difference summoning spells , one that summon 2 mages , one that summon 2 melees and one that summon 1 mage and 1 melee , he will cast one of them randomly.
the only problem with them that they feel like they are on passive mode and don't aggro straight away.

> Mechanics comments on Rage Winterchill
> Frost Armor - nowhere to be seen - BUG

Are you sure about this one ? he uses it every 30-45sec and might get delayed sometime if he is casting D&D
the spell exist in every test i have done so far (mostly solo)

> Mechanics comments on Kaz'rogal
> Mark of Kaz'rogal - Does not target whole raid - BUG

the Mark only target enemies that have mana , so rogue and warrior or shapeshifted druid (cat/bear) do not get the mark.

This was the most boss i am looking for raids to test in PTR as he have 13.4M health and have "enrage" timer of 210sec (3:30). Which imo is impossible even for top tier raids , specially that there is the Mark to slow caster dps and Cripple that lower melee dps.
Hope if there is more tests after some fixes that happened to his Mark.

- For Archimonde did you make sure he's not near the World Tree ? if Finger of Death you are talking about targeting multiple people at the same time then that's Hand of Death (+100k to each person) which trigger if he get closer to World Tree which is a wipe.

- I do feel like the distance check from World Tree is kind too big tho or the location is wrong from where to check for it , and also for Finger of Death it looks like it procs too very often with the slightest movement.

**Comment by IskrenPlashkov** [comment]
**_Crypt fiend: Web - does not work - BUG_** 

This is by no means a hill Im willing to die on. If staff decides its not a bug by all means lets go without it.

**_Shadowy Necromancer: Summon Skeletons - Currently summon both melee and ranged add at the same time. I believe it is supposed to be one or the other. Possible bug._**

I was unaware of that distinction in summoning, did not find it in the sources I checked. 

**_Mechanics comments on Rage Winterchill Frost Armor - nowhere to be seen - BUG_**

We never saw it in proper raid setting nor when I was solo testing shortly after to verify our findings. If it was popping for you, did u try dispelling it ?

**_Mechanics comments on Kaz'rogal Mark of Kaz'rogal - Does not target whole raid - BUG_**

Perhaps I should have phrased it better. There were mana users not being targeted by the mark on regular basis. 

- For Archimonde did you make sure he's not near the World Tree ? if Finger of Death you are talking about targeting multiple people at the same time then that's Hand of Death (+100k to each person) which trigger if he get closer to World Tree which is a wipe.
- 
- I do feel like the distance check from World Tree is kind too big tho or the location is wrong from where to check for it , and also for Finger of Death it looks like it procs too very often with the slightest movement.

We knew proximity to world tree is an issue so we made sure to keep him far away from it. That being said, if for whatever reason his or the tree's hitbox are larger he could have theoretically "reach" it and trigger the finger off death. Will need to test this further.

**Comment by amed80** [comment]
> Mechanics comments on Rage Winterchill Frost Armor - nowhere to be seen - BUG
> 
> We never saw it in proper raid setting nor when I was solo testing shortly after to verify our findings. If it was popping for you, did u try dispelling it ?

I guess something got broken while being in a raid? from my solo testing it , you can't steal the Frost Armor or remove it with Purge from Rage Winterchill but you can dispel the debuff from the players , Hand of Freedom can keep you free from getting the debuff for the whole time Rage Winterchill have Frost Armor on (10sec) , those the only things that i have tested with it.

> Mechanics comments on Kaz'rogal Mark of Kaz'rogal - Does not target whole raid - BUG
> Perhaps I should have phrased it better. There were mana users not being targeted by the mark on regular basis.

do you have shadow resistance on ? (priest buff or pala aura)
Mark of Kaz'rogal can be resisted , even if you get the debuff there is also a chance you may resist the explosion as both work as separate spells (explosion should be working now if you gonna test it in the future again)

If Archimonde is casting the single target spell that kills people (around 20k damage) then yes that's Finger of Death which currently is casted when ever there is no one in melee range.
This spell probably need like a delay before he check for a player in melee range before being casted if he's spamming it too often

For the World Tree check , i think this probably the range currently exist for it
![image](https://github.com/chromiecraft/PTR-review/assets/8395873/5aeff7af-a41b-49b3-924d-52d154016042)

As long he doesn't get closer to that circle he shouldn't use Hand of Death which target EVERYONE in the raid at the same time and he gonna be spamming it until everyone is dead.

**Comment by amed80** [comment]
this is for Frost Armor , you can see at the end using Cleanse to dispel it.

https://github.com/chromiecraft/PTR-review/assets/8395873/a521495b-7977-4811-9ead-bbd8d04d84d9
